name: send-reviews
on:
  schedule:
    - cron: 0 6 * * *

jobs:
  send-reviews:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Send send-reviews
      run: |
        make docker-run
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        COURSE_ID: ${{ secrets.COURSE_ID }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
